services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  ServerShellBundle\Controller\:
    resource: '../../Controller/'
  ServerShellBundle\DataFixtures\:
    resource: '../../DataFixtures/'
  ServerShellBundle\MessageHandler\:
    resource: '../../MessageHandler/'
  ServerShellBundle\Repository\:
    resource: '../../Repository/'
  ServerShellBundle\Service\:
    resource: '../../Service/'
